imports:
  # Content
  # -> Hugolify content types and taxonomies available https://www.hugolify.io/docs/sections/

  # Core theme
  - path: github.com/hugolify/hugolify-theme-1
  - path: github.com/hugolify/hugolify-theme

  - path: github.com/hugolify/hugolify-theme-posts
  - path: github.com/hugolify/hugolify-theme-publications

  # CMS
  - path: github.com/hugolify/hugolify-decap-cms
